# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePassword(object):
    def setupUi(self, ChangePassword):
        ChangePassword.setObjectName("ChangePassword")
        ChangePassword.resize(610, 744)
        ChangePassword.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        ChangePassword.setStyleSheet("background-color: #003EBB;")
        self.label_title = QtWidgets.QLabel(ChangePassword)
        self.label_title.setGeometry(QtCore.QRect(0, 290, 591, 41))
        self.label_title.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"font-size: 24px;\n"
"color: yellow;\n"
"")
        self.label_title.setObjectName("label_title")
        self.btn_back = QtWidgets.QPushButton(ChangePassword)
        self.btn_back.setGeometry(QtCore.QRect(100, 600, 161, 51))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.btn_change_pw = QtWidgets.QPushButton(ChangePassword)
        self.btn_change_pw.setGeometry(QtCore.QRect(330, 600, 161, 51))
        self.btn_change_pw.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_change_pw.setObjectName("btn_change_pw")
        self.label_user_acc = QtWidgets.QLabel(ChangePassword)
        self.label_user_acc.setGeometry(QtCore.QRect(0, 340, 591, 21))
        self.label_user_acc.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"font-size: 15px;\n"
"color: white;\n"
"")
        self.label_user_acc.setObjectName("label_user_acc")
        self.txt_pass = QtWidgets.QLineEdit(ChangePassword)
        self.txt_pass.setGeometry(QtCore.QRect(150, 390, 341, 31))
        self.txt_pass.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pass.setObjectName("txt_pass")
        self.txt_confirm = QtWidgets.QLineEdit(ChangePassword)
        self.txt_confirm.setGeometry(QtCore.QRect(150, 510, 341, 31))
        self.txt_confirm.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_confirm.setObjectName("txt_confirm")
        self.icon_confirm = QtWidgets.QLabel(ChangePassword)
        self.icon_confirm.setGeometry(QtCore.QRect(100, 500, 41, 41))
        self.icon_confirm.setText("")
        self.icon_confirm.setPixmap(QtGui.QPixmap("C:/Users/User/.designer/backup/images/confirm icon.png"))
        self.icon_confirm.setScaledContents(True)
        self.icon_confirm.setObjectName("icon_confirm")
        self.txt_new_pass = QtWidgets.QLineEdit(ChangePassword)
        self.txt_new_pass.setGeometry(QtCore.QRect(150, 450, 341, 31))
        self.txt_new_pass.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_new_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_new_pass.setObjectName("txt_new_pass")
        self.label_pass_icon = QtWidgets.QLabel(ChangePassword)
        self.label_pass_icon.setGeometry(QtCore.QRect(100, 440, 41, 51))
        self.label_pass_icon.setText("")
        self.label_pass_icon.setPixmap(QtGui.QPixmap("C:/Users/User/.designer/backup/images/pass_icon.png"))
        self.label_pass_icon.setScaledContents(True)
        self.label_pass_icon.setObjectName("label_pass_icon")
        self.label_pass_icon_2 = QtWidgets.QLabel(ChangePassword)
        self.label_pass_icon_2.setGeometry(QtCore.QRect(100, 380, 41, 51))
        self.label_pass_icon_2.setText("")
        self.label_pass_icon_2.setPixmap(QtGui.QPixmap("C:/Users/User/.designer/backup/images/pass_icon.png"))
        self.label_pass_icon_2.setScaledContents(True)
        self.label_pass_icon_2.setObjectName("label_pass_icon_2")
        self.image_main = QtWidgets.QLabel(ChangePassword)
        self.image_main.setGeometry(QtCore.QRect(150, 20, 301, 251))
        self.image_main.setText("")
        self.image_main.setPixmap(QtGui.QPixmap("images/main_image.png"))
        self.image_main.setScaledContents(True)
        self.image_main.setObjectName("image_main")
        self.label_error = QtWidgets.QLabel(ChangePassword)
        self.label_error.setGeometry(QtCore.QRect(110, 540, 391, 51))
        self.label_error.setStyleSheet("font-size: 15px;\n"
"color: red;\n"
"qproperty-alignment: AlignCenter;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_error.setWordWrap(True)
        self.label_error.setObjectName("label_error")

        self.retranslateUi(ChangePassword)
        QtCore.QMetaObject.connectSlotsByName(ChangePassword)
        ChangePassword.setTabOrder(self.txt_pass, self.txt_new_pass)
        ChangePassword.setTabOrder(self.txt_new_pass, self.txt_confirm)
        ChangePassword.setTabOrder(self.txt_confirm, self.btn_change_pw)
        ChangePassword.setTabOrder(self.btn_change_pw, self.btn_back)

    def retranslateUi(self, ChangePassword):
        _translate = QtCore.QCoreApplication.translate
        ChangePassword.setWindowTitle(_translate("ChangePassword", "Dialog"))
        self.label_title.setText(_translate("ChangePassword", "C H A N G E     P A S S W O R D"))
        self.btn_back.setText(_translate("ChangePassword", "<< BACK"))
        self.btn_change_pw.setText(_translate("ChangePassword", "Change Password"))
        self.label_user_acc.setText(_translate("ChangePassword", "Account: <User>"))
        self.txt_pass.setPlaceholderText(_translate("ChangePassword", " C u r r e n t      P a s s w o r d"))
        self.txt_confirm.setPlaceholderText(_translate("ChangePassword", " C o n f i r m   N e w    P a s s w o r d"))
        self.txt_new_pass.setPlaceholderText(_translate("ChangePassword", " N e w       P a s s w o r d"))
        self.label_error.setText(_translate("ChangePassword", "Password and Confirm Password do not match"))
