# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateWindow(object):
    def setupUi(self, CreateWindow):
        CreateWindow.setObjectName("CreateWindow")
        CreateWindow.resize(596, 744)
        CreateWindow.setStyleSheet("background-color: #003EBB;")
        self.btn_create = QtWidgets.QPushButton(CreateWindow)
        self.btn_create.setGeometry(QtCore.QRect(350, 630, 151, 51))
        self.btn_create.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_create.setObjectName("btn_create")
        self.btn_back = QtWidgets.QPushButton(CreateWindow)
        self.btn_back.setGeometry(QtCore.QRect(100, 630, 151, 51))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.label_user_icon = QtWidgets.QLabel(CreateWindow)
        self.label_user_icon.setGeometry(QtCore.QRect(110, 410, 41, 41))
        self.label_user_icon.setText("")
        self.label_user_icon.setPixmap(QtGui.QPixmap("images/user_icon.png"))
        self.label_user_icon.setScaledContents(True)
        self.label_user_icon.setObjectName("label_user_icon")
        self.label_pass_icon = QtWidgets.QLabel(CreateWindow)
        self.label_pass_icon.setGeometry(QtCore.QRect(110, 460, 41, 51))
        self.label_pass_icon.setText("")
        self.label_pass_icon.setPixmap(QtGui.QPixmap("images/pass_icon.png"))
        self.label_pass_icon.setScaledContents(True)
        self.label_pass_icon.setObjectName("label_pass_icon")
        self.label_image = QtWidgets.QLabel(CreateWindow)
        self.label_image.setGeometry(QtCore.QRect(100, 40, 371, 291))
        self.label_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("images/main_image.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.label_main = QtWidgets.QLabel(CreateWindow)
        self.label_main.setGeometry(QtCore.QRect(100, 350, 391, 31))
        self.label_main.setStyleSheet("font-size: 24px;\n"
"color: \"#FFFB00\";")
        self.label_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main.setObjectName("label_main")
        self.txt_user = QtWidgets.QLineEdit(CreateWindow)
        self.txt_user.setGeometry(QtCore.QRect(160, 410, 341, 31))
        self.txt_user.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_user.setObjectName("txt_user")
        self.txt_pass = QtWidgets.QLineEdit(CreateWindow)
        self.txt_pass.setGeometry(QtCore.QRect(160, 470, 341, 31))
        self.txt_pass.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pass.setObjectName("txt_pass")
        self.txt_confirm = QtWidgets.QLineEdit(CreateWindow)
        self.txt_confirm.setGeometry(QtCore.QRect(160, 530, 341, 31))
        self.txt_confirm.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_confirm.setObjectName("txt_confirm")
        self.label_5 = QtWidgets.QLabel(CreateWindow)
        self.label_5.setGeometry(QtCore.QRect(110, 520, 41, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/confirm icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_error = QtWidgets.QLabel(CreateWindow)
        self.label_error.setGeometry(QtCore.QRect(110, 570, 391, 51))
        self.label_error.setStyleSheet("font-size: 15px;\n"
"color: red;\n"
"qproperty-alignment: AlignCenter;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_error.setWordWrap(True)
        self.label_error.setObjectName("label_error")

        self.retranslateUi(CreateWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateWindow)

    def retranslateUi(self, CreateWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateWindow.setWindowTitle(_translate("CreateWindow", "Dialog"))
        self.btn_create.setText(_translate("CreateWindow", "Create Account"))
        self.btn_back.setText(_translate("CreateWindow", "<< BACK"))
        self.label_main.setText(_translate("CreateWindow", "PASSWORD VAULT"))
        self.txt_user.setPlaceholderText(_translate("CreateWindow", " U s e r n a m e"))
        self.txt_pass.setPlaceholderText(_translate("CreateWindow", " P a s s w o r d"))
        self.txt_confirm.setPlaceholderText(_translate("CreateWindow", " C o n f i r m      P a s s w o r d"))
        self.label_error.setText(_translate("CreateWindow", "Password and Confirm Password do not match"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateWindow = QtWidgets.QDialog()
    ui = Ui_CreateWindow()
    ui.setupUi(CreateWindow)
    CreateWindow.show()
    sys.exit(app.exec_())
