# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 743)
        MainWindow.setStyleSheet("background-color: #003EBB;")
        self.btn_login = QtWidgets.QPushButton(MainWindow)
        self.btn_login.setGeometry(QtCore.QRect(100, 630, 151, 51))
        self.btn_login.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.btn_create = QtWidgets.QPushButton(MainWindow)
        self.btn_create.setGeometry(QtCore.QRect(350, 630, 151, 51))
        self.btn_create.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_create.setObjectName("btn_create")
        self.label_user_icon = QtWidgets.QLabel(MainWindow)
        self.label_user_icon.setGeometry(QtCore.QRect(110, 450, 41, 41))
        self.label_user_icon.setText("")
        self.label_user_icon.setPixmap(QtGui.QPixmap("images/user_icon.png"))
        self.label_user_icon.setScaledContents(True)
        self.label_user_icon.setObjectName("label_user_icon")
        self.label_image = QtWidgets.QLabel(MainWindow)
        self.label_image.setGeometry(QtCore.QRect(90, 60, 401, 311))
        self.label_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("images/main_image.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.label_main = QtWidgets.QLabel(MainWindow)
        self.label_main.setGeometry(QtCore.QRect(100, 390, 391, 31))
        self.label_main.setStyleSheet("font-size: 24px;\n"
"color: \"#FFFB00\";")
        self.label_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_main.setObjectName("label_main")
        self.txt_username = QtWidgets.QLineEdit(MainWindow)
        self.txt_username.setGeometry(QtCore.QRect(160, 450, 341, 31))
        self.txt_username.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(MainWindow)
        self.txt_password.setGeometry(QtCore.QRect(160, 530, 341, 31))
        self.txt_password.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"background-color : \"#FFFFFF\";\n"
"border : 1px solid;\n"
"font-size: 18px;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_pass_icon = QtWidgets.QLabel(MainWindow)
        self.label_pass_icon.setGeometry(QtCore.QRect(110, 510, 41, 51))
        self.label_pass_icon.setText("")
        self.label_pass_icon.setPixmap(QtGui.QPixmap("images/pass_icon.png"))
        self.label_pass_icon.setScaledContents(True)
        self.label_pass_icon.setObjectName("label_pass_icon")
        self.label_error = QtWidgets.QLabel(MainWindow)
        self.label_error.setGeometry(QtCore.QRect(110, 580, 391, 20))
        self.label_error.setStyleSheet("font-size: 15px;\n"
"color: \"#FF3939\";\n"
"qproperty-alignment: AlignCenter;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_error.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_error.setWordWrap(True)
        self.label_error.setObjectName("label_error")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.btn_login.setText(_translate("MainWindow", "LOG - IN"))
        self.btn_create.setText(_translate("MainWindow", "Create Account"))
        self.label_main.setText(_translate("MainWindow", "PASSWORD VAULT"))
        self.txt_username.setPlaceholderText(_translate("MainWindow", " U s e r n a m e"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", " P a s s w o r d"))
        self.label_error.setText(_translate("MainWindow", "Invalid Username or Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
