# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileDialog(object):
    def setupUi(self, ProfileDialog):
        ProfileDialog.setObjectName("ProfileDialog")
        ProfileDialog.resize(596, 742)
        ProfileDialog.setStyleSheet("background-color :  #003EBB; ")
        self.btn_save = QtWidgets.QPushButton(ProfileDialog)
        self.btn_save.setGeometry(QtCore.QRect(390, 630, 131, 41))
        self.btn_save.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.img_user = QtWidgets.QLabel(ProfileDialog)
        self.img_user.setGeometry(QtCore.QRect(90, 470, 41, 41))
        self.img_user.setText("")
        self.img_user.setPixmap(QtGui.QPixmap("images/user_icon.png"))
        self.img_user.setScaledContents(True)
        self.img_user.setObjectName("img_user")
        self.img_pass = QtWidgets.QLabel(ProfileDialog)
        self.img_pass.setGeometry(QtCore.QRect(90, 530, 41, 41))
        self.img_pass.setText("")
        self.img_pass.setPixmap(QtGui.QPixmap("images/pass_icon.png"))
        self.img_pass.setScaledContents(True)
        self.img_pass.setObjectName("img_pass")
        self.btn_back = QtWidgets.QPushButton(ProfileDialog)
        self.btn_back.setGeometry(QtCore.QRect(90, 630, 131, 41))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.label_main = QtWidgets.QLabel(ProfileDialog)
        self.label_main.setGeometry(QtCore.QRect(70, 380, 471, 20))
        self.label_main.setStyleSheet("font-size: 18px;\n"
"color: \"yellow\";\n"
"font-weight: bold;\n"
"qproperty-alignment: AlignCenter;")
        self.label_main.setObjectName("label_main")
        self.btn_generate = QtWidgets.QPushButton(ProfileDialog)
        self.btn_generate.setGeometry(QtCore.QRect(240, 630, 131, 41))
        self.btn_generate.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_generate.setObjectName("btn_generate")
        self.label_error = QtWidgets.QLabel(ProfileDialog)
        self.label_error.setGeometry(QtCore.QRect(80, 590, 461, 20))
        self.label_error.setStyleSheet("font-size: 15px;\n"
"color: \"#FF3939\";\n"
"qproperty-alignment: AlignCenter;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label_error.setObjectName("label_error")
        self.img_user_2 = QtWidgets.QLabel(ProfileDialog)
        self.img_user_2.setGeometry(QtCore.QRect(90, 410, 41, 41))
        self.img_user_2.setText("")
        self.img_user_2.setPixmap(QtGui.QPixmap("images/account icon.png"))
        self.img_user_2.setScaledContents(True)
        self.img_user_2.setObjectName("img_user_2")
        self.txt_pass = QtWidgets.QLineEdit(ProfileDialog)
        self.txt_pass.setGeometry(QtCore.QRect(140, 540, 381, 31))
        self.txt_pass.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : #FFFFFF;\n"
"border : 1px solid;\n"
"font-size: 17px;")
        self.txt_pass.setObjectName("txt_pass")
        self.txt_user = QtWidgets.QLineEdit(ProfileDialog)
        self.txt_user.setGeometry(QtCore.QRect(140, 480, 381, 31))
        self.txt_user.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : #FFFFFF;\n"
"border : 1px solid;\n"
"font-size: 17px;")
        self.txt_user.setObjectName("txt_user")
        self.txt_account = QtWidgets.QLineEdit(ProfileDialog)
        self.txt_account.setGeometry(QtCore.QRect(140, 420, 381, 31))
        self.txt_account.setStyleSheet("border-radius : 5px;\n"
"font-family: \"sans-serif\";\n"
"height : 34px;\n"
"font-weight: 1;\n"
"background-color : #FFFFFF;\n"
"border : 1px solid;\n"
"font-size: 17px;")
        self.txt_account.setObjectName("txt_account")
        self.label_image = QtWidgets.QLabel(ProfileDialog)
        self.label_image.setGeometry(QtCore.QRect(80, 30, 401, 311))
        self.label_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("images/main_image.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")

        self.retranslateUi(ProfileDialog)
        QtCore.QMetaObject.connectSlotsByName(ProfileDialog)
        ProfileDialog.setTabOrder(self.txt_account, self.txt_user)
        ProfileDialog.setTabOrder(self.txt_user, self.txt_pass)
        ProfileDialog.setTabOrder(self.txt_pass, self.btn_back)
        ProfileDialog.setTabOrder(self.btn_back, self.btn_generate)
        ProfileDialog.setTabOrder(self.btn_generate, self.btn_save)

    def retranslateUi(self, ProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        ProfileDialog.setWindowTitle(_translate("ProfileDialog", "Dialog"))
        self.btn_save.setText(_translate("ProfileDialog", "Save "))
        self.btn_back.setText(_translate("ProfileDialog", "BACK"))
        self.label_main.setText(_translate("ProfileDialog", "ADD   AN   ENTRY"))
        self.btn_generate.setText(_translate("ProfileDialog", "Generate"))
        self.label_error.setText(_translate("ProfileDialog", "Please Enter All Fields"))
        self.txt_pass.setPlaceholderText(_translate("ProfileDialog", " Enter or Generate a Password"))
        self.txt_user.setPlaceholderText(_translate("ProfileDialog", " Enter the Username for that App"))
        self.txt_account.setPlaceholderText(_translate("ProfileDialog", "Enter the Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileDialog = QtWidgets.QDialog()
    ui = Ui_ProfileDialog()
    ui.setupUi(ProfileDialog)
    ProfileDialog.show()
    sys.exit(app.exec_())
