# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(597, 739)
        Profile.setStyleSheet("background-color: #003EBB;\n"
"color : white;\n"
"\n"
"QPushButton#Ok{\n"
"    background-color: #F87E2E;\n"
"    color: white;\n"
"}")
        self.label_greet = QtWidgets.QLabel(Profile)
        self.label_greet.setGeometry(QtCore.QRect(0, 0, 601, 61))
        self.label_greet.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"font-size: 24px;\n"
"color: yellow;\n"
"")
        self.label_greet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_greet.setObjectName("label_greet")
        self.btn_show = QtWidgets.QPushButton(Profile)
        self.btn_show.setGeometry(QtCore.QRect(160, 60, 131, 41))
        self.btn_show.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_show.setObjectName("btn_show")
        self.btn_add = QtWidgets.QPushButton(Profile)
        self.btn_add.setGeometry(QtCore.QRect(300, 60, 131, 41))
        self.btn_add.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.btn_logout = QtWidgets.QPushButton(Profile)
        self.btn_logout.setGeometry(QtCore.QRect(20, 60, 131, 41))
        self.btn_logout.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_logout.setObjectName("btn_logout")
        self.label_app = QtWidgets.QLabel(Profile)
        self.label_app.setGeometry(QtCore.QRect(50, 120, 101, 20))
        self.label_app.setStyleSheet("color:white;\n"
"font-family:san-serif;\n"
"font-weight:bold;\n"
"")
        self.label_app.setObjectName("label_app")
        self.label_user = QtWidgets.QLabel(Profile)
        self.label_user.setGeometry(QtCore.QRect(200, 120, 71, 20))
        self.label_user.setStyleSheet("color:white;\n"
"font-family:san-serif;\n"
"font-weight:bold;\n"
"")
        self.label_user.setObjectName("label_user")
        self.label_pw = QtWidgets.QLabel(Profile)
        self.label_pw.setGeometry(QtCore.QRect(330, 120, 71, 20))
        self.label_pw.setStyleSheet("color:white;\n"
"font-family:san-serif;\n"
"font-weight:bold;\n"
"")
        self.label_pw.setObjectName("label_pw")
        self.btn_setting = QtWidgets.QPushButton(Profile)
        self.btn_setting.setGeometry(QtCore.QRect(440, 60, 131, 41))
        self.btn_setting.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_setting.setObjectName("btn_setting")
        self.container = QtWidgets.QScrollArea(Profile)
        self.container.setGeometry(QtCore.QRect(0, 150, 601, 591))
        self.container.setStyleSheet("background-color: #FFE790")
        self.container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.container.setWidgetResizable(True)
        self.container.setObjectName("container")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.container.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Dialog"))
        self.label_greet.setText(_translate("Profile", "Hello <USER>! "))
        self.btn_show.setText(_translate("Profile", "Show Accounts"))
        self.btn_add.setText(_translate("Profile", "Add Account"))
        self.btn_logout.setText(_translate("Profile", "LOG OUT"))
        self.label_app.setText(_translate("Profile", "APPLICATION"))
        self.label_user.setText(_translate("Profile", "USERNAME"))
        self.label_pw.setText(_translate("Profile", "PASSWORD"))
        self.btn_setting.setText(_translate("Profile", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Profile = QtWidgets.QDialog()
    ui = Ui_Profile()
    ui.setupUi(Profile)
    Profile.show()
    sys.exit(app.exec_())
