# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(596, 744)
        Settings.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Settings.setStyleSheet("background-color: #003EBB;")
        self.label_title = QtWidgets.QLabel(Settings)
        self.label_title.setGeometry(QtCore.QRect(0, 490, 591, 41))
        self.label_title.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"font-size: 24px;\n"
"color: yellow;\n"
"")
        self.label_title.setObjectName("label_title")
        self.btn_back = QtWidgets.QPushButton(Settings)
        self.btn_back.setGeometry(QtCore.QRect(40, 590, 161, 51))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.btn_delete_acc = QtWidgets.QPushButton(Settings)
        self.btn_delete_acc.setGeometry(QtCore.QRect(400, 590, 161, 51))
        self.btn_delete_acc.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_delete_acc.setObjectName("btn_delete_acc")
        self.label_image = QtWidgets.QLabel(Settings)
        self.label_image.setGeometry(QtCore.QRect(40, 40, 501, 421))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("images/main_image.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.btn_change_pw = QtWidgets.QPushButton(Settings)
        self.btn_change_pw.setGeometry(QtCore.QRect(220, 590, 161, 51))
        self.btn_change_pw.setStyleSheet("QPushButton{\n"
"    font-size : 15px;\n"
"    background-color : \"#F87E2E\";\n"
"    color: \"white\";\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color : \"#FFD139\";\n"
"}")
        self.btn_change_pw.setObjectName("btn_change_pw")
        self.label_user_acc = QtWidgets.QLabel(Settings)
        self.label_user_acc.setGeometry(QtCore.QRect(0, 530, 591, 21))
        self.label_user_acc.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"font-size: 15px;\n"
"color: white;\n"
"")
        self.label_user_acc.setObjectName("label_user_acc")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.btn_back, self.btn_change_pw)
        Settings.setTabOrder(self.btn_change_pw, self.btn_delete_acc)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.label_title.setText(_translate("Settings", "U S E R      S E T T I N G S"))
        self.btn_back.setText(_translate("Settings", "<< BACK"))
        self.btn_delete_acc.setText(_translate("Settings", "Delete Account"))
        self.btn_change_pw.setText(_translate("Settings", "Change Password"))
        self.label_user_acc.setText(_translate("Settings", "Account: <User>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
